.\" Man page for the TreeNode class included in Salamapper library
.\" Contact nooberieno.dev@gmail.com to correct errors or typos
.TH man 3 "30 October 2024" "0.1" "Salamapper library functions man pages"
.SH NAME
.SH SYNOPSIS
.SH DESCRIPTION
.SH SEE ALSO
.SH AUTHOR
Nooberieno
.SH COPYRIGHT
This library is licensed under the MIT license under the Copyright (c) 2024 Nooberieno